name: Publish Container

on:
  push:
    branches: [ chief ]
  pull_request:
    branches: [ chief ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: TheQuib
        password: ${{ secrets.GH_CONTAINER_REGISTRY_SECRET }}

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_TOKEN }}
    
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: true
        tags: |
          ghcr.io/TheQuib/nginx-docker:latest
          thequib/nginx-docker:latest