name: Publish Container

on:
  push:
    branches: [ chief ]
  pull_request:
    branches: [ chief ]
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GitHub-Packages-Container-Registry  }}
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/thequib/nginx-docker:latest
        docker run ghcr.io/thequib/nginx-docker:latest
        docker push ghcr.io/qhequib/nginx-docker:latest
