name: Docker Image CI

on:
  push:
    branches: [ chief ]
  pull_request:
    branches: [ chief ]
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nginx-docker:latest
        docker run ghcr.io/TheQuib/nginx-docker:latest
        docker push ghcr.io/TheQuib/nginx-docker:latest
